import { lazy, type ComponentType } from 'react';

export interface RouteConfig {
  path: string;
  title: string;
  component: ComponentType;
  category: string;
  /** Which library shelf this belongs to */
  shelf?: string;
  /** Content file slug (filename without .md) */
  slug?: string;
}

export const routes: RouteConfig[] = [
  {
    path: '/',
    title: 'Developer Open Book',
    component: lazy(() => import('./pages/index')),
    category: 'Home',
  },

  // ═══ DART (23 docs) ═══
  { path: '/dart-roadmap-overview', title: 'Dart 학습 로드맵', component: lazy(() => import('./pages/dart-roadmap-overview')), category: 'Overview', shelf: 'dart', slug: 'dart-roadmap-overview' },
  { path: '/dart-step01-overview-and-setup', title: 'Step 1 - Dart 개요 및 환경 구축', component: lazy(() => import('./pages/dart-step01-overview-and-setup')), category: 'Phase 1: 기초', shelf: 'dart', slug: 'dart-step01-overview-and-setup' },
  { path: '/dart-step02-variables-and-types', title: 'Step 2 - 변수와 데이터 타입', component: lazy(() => import('./pages/dart-step02-variables-and-types')), category: 'Phase 1: 기초', shelf: 'dart', slug: 'dart-step02-variables-and-types' },
  { path: '/dart-step03-operators-and-conditionals', title: 'Step 3 - 연산자와 조건문', component: lazy(() => import('./pages/dart-step03-operators-and-conditionals')), category: 'Phase 1: 기초', shelf: 'dart', slug: 'dart-step03-operators-and-conditionals' },
  { path: '/dart-step04-loops', title: 'Step 4 - 반복문', component: lazy(() => import('./pages/dart-step04-loops')), category: 'Phase 1: 기초', shelf: 'dart', slug: 'dart-step04-loops' },
  { path: '/dart-step05-functions', title: 'Step 5 - 함수', component: lazy(() => import('./pages/dart-step05-functions')), category: 'Phase 1: 기초', shelf: 'dart', slug: 'dart-step05-functions' },
  { path: '/dart-step06-collections', title: 'Step 6 - Collection 타입', component: lazy(() => import('./pages/dart-step06-collections')), category: 'Phase 2: 핵심', shelf: 'dart', slug: 'dart-step06-collections' },
  { path: '/dart-step07-collections-advanced', title: 'Step 7 - Collection 고급', component: lazy(() => import('./pages/dart-step07-collections-advanced')), category: 'Phase 2: 핵심', shelf: 'dart', slug: 'dart-step07-collections-advanced' },
  { path: '/dart-step08-classes-and-objects', title: 'Step 8 - 클래스와 객체', component: lazy(() => import('./pages/dart-step08-classes-and-objects')), category: 'Phase 2: 핵심', shelf: 'dart', slug: 'dart-step08-classes-and-objects' },
  { path: '/dart-step09-constructors', title: 'Step 9 - 생성자 패턴', component: lazy(() => import('./pages/dart-step09-constructors')), category: 'Phase 2: 핵심', shelf: 'dart', slug: 'dart-step09-constructors' },
  { path: '/dart-step10-oop-extends', title: 'Step 10 - OOP 확장', component: lazy(() => import('./pages/dart-step10-oop-extends')), category: 'Phase 2: 핵심', shelf: 'dart', slug: 'dart-step10-oop-extends' },
  { path: '/dart-step11-mixins', title: 'Step 11 - Mixins', component: lazy(() => import('./pages/dart-step11-mixins')), category: 'Phase 2: 핵심', shelf: 'dart', slug: 'dart-step11-mixins' },
  { path: '/dart-step12-enums', title: 'Step 12 - 열거형', component: lazy(() => import('./pages/dart-step12-enums')), category: 'Phase 2: 핵심', shelf: 'dart', slug: 'dart-step12-enums' },
  { path: '/dart-step13-exception-handling', title: 'Step 13 - 예외 처리', component: lazy(() => import('./pages/dart-step13-exception-handling')), category: 'Phase 2: 핵심', shelf: 'dart', slug: 'dart-step13-exception-handling' },
  { path: '/dart-step14-async-future-stream', title: 'Step 14 - 비동기 프로그래밍', component: lazy(() => import('./pages/dart-step14-async-future-stream')), category: 'Phase 3: 심화', shelf: 'dart', slug: 'dart-step14-async-future-stream' },
  { path: '/dart-step15-isolates', title: 'Step 15 - Isolate와 병렬 컴퓨팅', component: lazy(() => import('./pages/dart-step15-isolates')), category: 'Phase 3: 심화', shelf: 'dart', slug: 'dart-step15-isolates' },
  { path: '/dart-step16-generics', title: 'Step 16 - 제네릭', component: lazy(() => import('./pages/dart-step16-generics')), category: 'Phase 3: 심화', shelf: 'dart', slug: 'dart-step16-generics' },
  { path: '/dart-step17-extensions', title: 'Step 17 - Extension 메서드', component: lazy(() => import('./pages/dart-step17-extensions')), category: 'Phase 3: 심화', shelf: 'dart', slug: 'dart-step17-extensions' },
  { path: '/dart-step18-sealed-patterns', title: 'Step 18 - Sealed Class & 패턴 매칭', component: lazy(() => import('./pages/dart-step18-sealed-patterns')), category: 'Phase 3: 심화', shelf: 'dart', slug: 'dart-step18-sealed-patterns' },
  { path: '/dart-step19-records', title: 'Step 19 - Records', component: lazy(() => import('./pages/dart-step19-records')), category: 'Phase 3: 심화', shelf: 'dart', slug: 'dart-step19-records' },
  { path: '/dart-step20-functional', title: 'Step 20 - 함수형 프로그래밍 심화', component: lazy(() => import('./pages/dart-step20-functional')), category: 'Phase 4: 실전', shelf: 'dart', slug: 'dart-step20-functional' },
  { path: '/dart-step21-testing', title: 'Step 21 - 테스트와 디버깅', component: lazy(() => import('./pages/dart-step21-testing')), category: 'Phase 4: 실전', shelf: 'dart', slug: 'dart-step21-testing' },
  { path: '/dart-step22-packages', title: 'Step 22 - 패키지와 pub.dev', component: lazy(() => import('./pages/dart-step22-packages')), category: 'Phase 4: 실전', shelf: 'dart', slug: 'dart-step22-packages' },

  // ═══ FLUTTER (31 docs) ═══
  { path: '/flutter', title: 'Flutter 학습 로드맵', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'flutter' },
  { path: '/step-01-flutter', title: 'Step 01 — Flutter 아키텍처', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-01-flutter' },
  { path: '/step-02-dart', title: 'Step 02 — Dart 언어 핵심', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-02-dart' },
  { path: '/step-03-flutter', title: 'Step 03 — Flutter 개발 환경', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-03-flutter' },
  { path: '/step-04-widget', title: 'Step 04 — Widget 개념', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-04-widget' },
  { path: '/step-05-statelesswidget-vs-statefulwidget', title: 'Step 05 — StatelessWidget vs StatefulWidget', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-05-statelesswidget-vs-statefulwidget' },
  { path: '/step-06-layout', title: 'Step 06 — Layout 시스템', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-06-layout' },
  { path: '/step-07-ui', title: 'Step 07 — 기본 UI 위젯', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-07-ui' },
  { path: '/step-08-material-design', title: 'Step 08 — Material Design 시스템', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-08-material-design' },
  { path: '/step-09', title: 'Step 09 — 사용자 입력 처리', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-09' },
  { path: '/step-10-form', title: 'Step 10 — Form 시스템', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-10-form' },
  { path: '/step-11-navigation', title: 'Step 11 — Navigation 시스템', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-11-navigation' },
  { path: '/step-12-flutter', title: 'Step 12 — Flutter 상태관리 개념', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-12-flutter' },
  { path: '/step-13-setstate', title: 'Step 13 — setState 심화', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-13-setstate' },
  { path: '/step-14-provider', title: 'Step 14 — Provider 패턴', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-14-provider' },
  { path: '/step-15', title: 'Step 15 — 고급 상태관리', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-15' },
  { path: '/step-16-future-async-ui', title: 'Step 16 — Future / Async UI', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-16-future-async-ui' },
  { path: '/step-17-http', title: 'Step 17 — HTTP 통신', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-17-http' },
  { path: '/step-18', title: 'Step 18 — 로컬 데이터 저장', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-18' },
  { path: '/step-19-animation', title: 'Step 19 — 애니메이션', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-19-animation' },
  { path: '/step-20-flutter-project-structure', title: 'Step 20 — Flutter 프로젝트 구조', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-20-flutter-project-structure' },
  { path: '/step-21-clean-architecture', title: 'Step 21 — Clean Architecture', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-21-clean-architecture' },
  { path: '/step-22-dependency-injection', title: 'Step 22 — Dependency Injection', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-22-dependency-injection' },
  { path: '/step-23-flutter-testing', title: 'Step 23 — Flutter 테스팅', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-23-flutter-testing' },
  { path: '/step-24-flutter-rendering-optimization', title: 'Step 24 — Flutter 렌더링 최적화', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-24-flutter-rendering-optimization' },
  { path: '/step-25-memory-management', title: 'Step 25 — 메모리 관리', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-25-memory-management' },
  { path: '/step-26-native-integration', title: 'Step 26 — Native 연동', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-26-native-integration' },
  { path: '/step-27-ai-integration', title: 'Step 27 — AI 통합', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-27-ai-integration' },
  { path: '/step-28-push-notifications', title: 'Step 28 — 푸시 알림', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-28-push-notifications' },
  { path: '/step-29-app-build-deploy', title: 'Step 29 — 앱 빌드 및 배포', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-29-app-build-deploy' },
  { path: '/step-30-cicd', title: 'Step 30 — CI/CD 자동화', component: lazy(() => import('./pages/BookPage')), category: 'Flutter', shelf: 'flutter', slug: 'step-30-cicd' },

  // ═══ REACT (43 docs) ═══
  { path: '/react-step00', title: 'React 완성 로드맵', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step00' },
  { path: '/react-step01', title: 'Step 01. 개발 환경 설치와 프로젝트 구조', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step01' },
  { path: '/react-step02', title: 'Step 02. 모던 JavaScript 필수 문법', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step02-JavaScript' },
  { path: '/react-step03', title: 'Step 03. React 생태계 조감도', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step03-React' },
  { path: '/react-step04', title: 'Step 04. JSX와 컴포넌트 실행 모델', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step04-JSX' },
  { path: '/react-step05', title: 'Step 05. Props와 단방향 데이터 흐름', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step05-Props' },
  { path: '/react-step06', title: 'Step 06. useState와 렌더 사이클', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step06-useState' },
  { path: '/react-step07', title: 'Step 07. Reconciliation과 Key 전략', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step07-Reconciliation-Key' },
  { path: '/react-step08', title: 'Step 08. Form과 Synthetic Event', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step08-Form-Synthetic-Event' },
  { path: '/react-step09', title: 'Step 09. 조건부 렌더링과 리스트 패턴', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step09' },
  { path: '/react-step10', title: 'Step 10. React 내부 구조 심층 분석', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step10-React' },
  { path: '/react-step11', title: 'Step 11. useEffect 완전 이해', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step11-useEffect' },
  { path: '/react-step12', title: 'Step 12. useRef와 DOM 접근 전략', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step12-useRef-DOM' },
  { path: '/react-step13', title: 'Step 13. useReducer와 상태 머신 설계', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step13-useReducer' },
  { path: '/react-step14', title: 'Step 14. 메모이제이션 전략', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step14' },
  { path: '/react-step15', title: 'Step 15. React 18/19 신규 Hooks', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step15-React-18-19-Hooks' },
  { path: '/react-step16', title: 'Step 16. Custom Hook 설계 패턴', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step16-Custom-Hook' },
  { path: '/react-step17', title: 'Step 17. Error Handling 아키텍처', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step17-Error-Handling' },
  { path: '/react-step18', title: 'Step 18. React Router v6+ 심화', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step18-ReactRouter-v6' },
  { path: '/react-step19', title: 'Step 19. 렌더링 전략 비교 분석', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step19' },
  { path: '/react-step20', title: 'Step 20. React Server Components', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step20-React-Server-Components' },
  { path: '/react-step21', title: 'Step 21. Next.js App Router 핵심', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step21-NextJS-App-Router' },
  { path: '/react-step22', title: 'Step 22. REST API 통합', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step22-REST-API' },
  { path: '/react-step23', title: 'Step 23. TanStack Query', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step23-TanStack-Query' },
  { path: '/react-step24', title: 'Step 24. API 계층 설계', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step24-API' },
  { path: '/react-step25', title: 'Step 25. Context API 심화', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step25-Context-API' },
  { path: '/react-step26', title: 'Step 26. 전역 상태 관리 (Zustand)', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step26-Zustand' },
  { path: '/react-step27', title: 'Step 27. 컴포넌트 설계 패턴', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step27' },
  { path: '/react-step28', title: 'Step 28. 프로젝트 구조와 아키텍처', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step28' },
  { path: '/react-step29', title: 'Step 29. 성능 최적화 심화', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step29' },
  { path: '/react-step30', title: 'Step 30. Suspense 아키텍처', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step30-Suspense' },
  { path: '/react-step31', title: 'Step 31. TypeScript와 React 통합', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step31-TypeScript-React' },
  { path: '/react-step32', title: 'Step 32. React Hook Form과 Zod', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step32-React-Hook-Form-Zod' },
  { path: '/react-step33', title: 'Step 33. 폼 UX 패턴과 접근성', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step33-UX' },
  { path: '/react-step34', title: 'Step 34. CSS 전략과 스타일링', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step34-CSS' },
  { path: '/react-step35', title: 'Step 35. 국제화와 접근성', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step35-i18n-a11y' },
  { path: '/react-step36', title: 'Step 36. 컴포넌트 테스트 (RTL)', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step36-RTL' },
  { path: '/react-step37', title: 'Step 37. E2E 테스트와 테스트 전략', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step37-E2E' },
  { path: '/react-step38', title: 'Step 38. 코드 품질과 개발 도구', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step38' },
  { path: '/react-step39', title: 'Step 39. Vite 빌드 시스템 심화', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step39-Vite' },
  { path: '/react-step40', title: 'Step 40. 배포 전략과 CI/CD', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step40-CICD' },
  { path: '/react-step41', title: 'Step 41. 프로덕션 모니터링', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step41' },
  { path: '/react-step42', title: 'Step 42. 종합 프로젝트', component: lazy(() => import('./pages/BookPage')), category: 'React', shelf: 'react', slug: 'react-step42' },
];
